const Actions = {
  GET_PAGING_PRODUCTS: "GET_PAGING_PRODUCTS",
  GOT_PAGING_PRODUCTS: "GOT_PAGING_PRODUCTS",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GOT_PRODUCT_BY_ID: "GOT_PRODUCT_BY_ID",
  INSERT_PRODUCT: "INSERT_PRODUCT",
  INSERTED_PRODUCT: "INSERTED_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATED_PRODUCT: "UPDATED_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETED_PRODUCT: "DELETED_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  GOT_CATEGORIES: "GOT_CATEGORIES",
  BAD_REQUEST_GOT: "BAD_REQUEST_GOT",
  INTERNAL_ERROR_GOT: "INTERNAL_ERROR_GOT",
};

export default Actions;
