const Actions = {
  GET_PAGING_PRODUCTS: "GET_PAGING_PRODUCTS",
  GOT_PAGING_PRODUCTS: "GOT_PAGING_PRODUCTS",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GOT_PRODUCT_BY_ID: "GOT_PRODUCT_BY_ID",
  INSERT_PRODUCT: "INSERT_PRODUCT",
  INSERTED_PRODUCT: "INSERTED_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  UPDATED_PRODUCT: "UPDATED_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  DELETED_PRODUCT: "DELETED_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  GOT_CATEGORIES: "GOT_CATEGORIES",
  GET_PAGING_CATEGORIES: "GET_PAGING_CATEGORIES",
  GOT_PAGING_CATEGORIES: "GOT_PAGING_CATEGORIES",
  GET_CATEGORY_BY_ID: "GET_CATEGORY_BY_ID",
  GOT_CATEGORY_BY_ID: "GOT_CATEGORY_BY_ID",
  BAD_REQUEST_GOT: "BAD_REQUEST_GOT",
  INTERNAL_ERROR_GOT: "INTERNAL_ERROR_GOT",
  SET_PRODUCT_PAGING_QUERY: "SET_PRODUCT_PAGING_QUERY",
  DONE_SET_PRODUCT_PAGING_QUERY: "DONE_SET_PRODUCT_PAGING_QUERY",
  SET_CATEGORY_PAGING_QUERY: "SET_CATEGORY_PAGING_QUERY",
  DONE_SET_CATEGORY_PAGING_QUERY: "DONE_SET_CATEGORY_PAGING_QUERY",
  
};

export default Actions;
