const Actions = {
  GET_PAGING_PRODUCTS: "GET_PAGING_PRODUCTS",
  GOT_PAGING_PRODUCTS: "GOT_PAGING_PRODUCTS",
  GET_CATEGORIES: "GET_CATEGORIES",
  GOT_CATEGORIES: "GOT_CATEGORIES",
};

export default Actions;
